// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnlcvpbfriibogdvhgbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhubGN2cGJmcmlpYm9nZHZoZ2JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDU0MDEsImV4cCI6MjA1ODkyMTQwMX0.JpzDBNHu7ac3EYvEUkKbXTvm0_bLRYYOuaNiU6LVkvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);